# Generated by Django 4.2.3 on 2023-07-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.CharField(max_length=185)),
                ('Price', models.IntegerField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=55)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Salary', models.IntegerField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('DOB', models.DateField(max_length=8)),
                ('Address', models.TextField()),
                ('PaymentStatus', models.CharField(max_length=55, null=True)),
                ('Price', models.IntegerField(max_length=55, null=True)),
                ('DueDate', models.DateField(null=True)),
                ('TimeStamp', models.DateField(auto_now_add=True)),
                ('SelectMembershipplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.membershipplan')),
                ('SelectTrainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.trainer')),
            ],
        ),
    ]
