# Generated by Django 4.2.3 on 2023-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_enrollment_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='DueDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
